services:
  web: 
    container_name: pixel_on_rails
    build: . 
    image: pirapattk/pixel-on-rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -b '0.0.0.0'"
    environment:
      - RAILS_ENV=${RAILS_ENV}
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-networks
    volumes:
      - .:/rails

networks:
  app-networks: